// SPDX-FileCopyrightText: 2022 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Jacob Tong <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <wrexbe@protonmail.com>
// SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 Rank #1 Jonestown partygoer <mary@thughunt.ing>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aviu00 <93730715+Aviu00@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Misandry <mary@thughunt.ing>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._CorvaxGoob.GhostBar.Controls;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client._CorvaxNext.UserInterface.Systems.Ghost.Controls;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }
<<<<<<< HEAD
    public GhostBarRulesWindow GhostBarWindow { get; } // Corvax-Next-GhostBar
    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? GhostBarPressed; // Corvax-Next-GhostBar
    
=======
    public GhostBarRulesWindow GhostBarWindow { get; } // CorvaxGoob-GhostBar

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? GhostBarPressed; // CorvaxGoob-GhostBar
>>>>>>> goob
    private int _prevNumberRoles;
    
    public GhostGui()
    {
        RobustXamlLoader.Load(this);
        TargetWindow = new GhostTargetWindow();
<<<<<<< HEAD
        GhostBarWindow = new GhostBarRulesWindow(); // Corvax-Next-GhostBar
=======

        GhostBarWindow = new GhostBarRulesWindow(); // CorvaxGoob-GhostBar

>>>>>>> goob
        MouseFilter = MouseFilterMode.Ignore;
        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
<<<<<<< HEAD
        GhostBarButton.OnPressed += _ => GhostBarPressed?.Invoke(); // Corvax-Next-GhostBar
=======
        GhostBarButton.OnPressed += _ => GhostBarPressed?.Invoke(); // CorvaxGoob-GhostBar
>>>>>>> goob
    }
    
    public void Hide()
    {
        TargetWindow.Close();
<<<<<<< HEAD
        GhostBarWindow.Close(); // Corvax-Next-GhostBar
        Visible = false;
    }
    
    public void Update(int? roles, bool? canReturnToBody)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
=======
        GhostBarWindow.Close(); // CorvaxGoob-GhostBar
        Visible = false;
    }

    // Ghoob edit && CorvaxGoob edit : GhostBar
    public void Update(int? roles, bool? canReturnToBody, bool? canEnterGhostBar = true, bool? canTakeGhostRoles = true)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        GhostBarButton.Disabled = !canEnterGhostBar ?? true; // CorvaxGoob-GhostBar
        // Goobstation start
        GhostRolesButton.Disabled = !canTakeGhostRoles ?? true;
        // Goobstation end

>>>>>>> goob
        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));
            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);
            }
            else if (roles == 0)
            {
                GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
            }
            _prevNumberRoles = (int)roles;
        }
        TargetWindow.Populate();
    }
    
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            TargetWindow.Dispose();
<<<<<<< HEAD
            GhostBarWindow.Dispose(); // Corvax-Next-GhostBar
=======
            GhostBarWindow.Dispose(); // CorvaxGoob-GhostBar
>>>>>>> goob
        }
    }
}
