- type: job
  id: ADTBlueShieldOfficer
  name: job-name-ADTBlueShieldOfficer
  description: job-description-ADTBlueShieldOfficer
  playTimeTracker: JobADTBlueShieldOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 13800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 13800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 13800 #3 hrs
  weight: 15
  startingGear: BlueShieldOfficerGear
  icon: "JobIconADTBlueShieldOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Captain
    - Command
    - Brig
    - Security
    - Armory
    - Maintenance
    - Service
    - External
    - Research
    - Medical
    - Engineering
    - Cargo
    - Centcom
    - BlueShield
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Skills # Corvax-Next-Skills
        skills:
        - ShuttleControl
        - Shooting
        - Surgery
        - MedicalEquipment

- type: startingGear
  id: BlueShieldOfficerGear
  equipment:
    head: ADTClothingHeadHatBeretBlueshieldBlack
    eyes: ADTClothingEyesGlassesBlueshield
    ears: ADTClothingHeadsetBlueshield
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    id: ADTBlueshieldOfficerPDA
    pocket1: WeaponX2DualphaseEnergyLaserGun
    neck: ADTClothingNeckCloakBlueshield
    back: ClothingBackpackBlueShield
    belt: ClothingBeltMilitaryWebbingBlueShieldFilled
- type: entity
  parent: ClothingBackpack
  id: ClothingBackpackBlueShield
  name: РИГ офицера "Синий Щит"
  description: Рюкзак офицера "Синий Щит" с функцией РИГ.
  components:
  - type: Sprite
    sprite: _Mini/Clothing/Back/blueshield.rsi
  - type: Storage
    grid:
    - 0,0,7,5
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 1
  - type: ToggleableClothing
    clothingPrototype: ADTBlueshieldSuit
    requiredSlot: BACK
    slot: outerClothing
  - type: ContainerContainer
    containers:
      toggleable-clothing: !type:ContainerSlot {}
      storagebase: !type:Container
        ents: []
  - type: StorageFill
    contents:
      - id: BoxSurvivalSecurity
      - id: Zipties
        amount: 3
      - id: MagazineMiniMachineGunBox
        amount: 3
      - id: WeaponMiniMachineGun
      - id: HandheldCrewMonitor
      - id: TrackingImplanter
        amount: 3
  - type: ExplosionResistance
    damageCoefficient: 0.6

