- type: gameMapPool
  id: DefaultMapPool
  maps:
  - NextBox
  - NextBagel
  - NextSilly
  - NextPacked
  - NextPaper
  - NextAvrite
  - NextOmega
  - NextDelta
  - NextMarathon
  - Oasis
  - Core
  - NextAmber
  - Plasma
  - NextAwesome
  - Fland